### PR TITLE
Added Files #111

### PR DESCRIPTION
**Pull request by prathmeshjani**
Added clean genome data .csv file format.

### CODE REVIEW

**Comment by vishalbarvaliya** [comment]
Great! LGTM!!

**Comment by Zarnagohil** [comment]
All data looks good to me.

**Comment by Nisha8898** [comment]
lgtm

**Review by karansorathiya — COMMENTED** [review]
LGTM

**Review by Nisha8898 — APPROVED** [review]

**Review by vishalbarvaliya — COMMENTED** [review]
Perfect!!

**Comment by MrunalWavdhane2303** [comment]
Looks good

**Comment by garima6876** [comment]
all is good !!

**Pull request merged**
