### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Nisha8898**
Upload the Jupyter Notebook file

### CODE REVIEW

**Comment by professor-greebie** [comment]
Better if I am left out of the review process.

**Comment by vishalbarvaliya** [comment]
lGTM!

**Comment by karansorathiya** [comment]
Looks good!!

**Comment by prathmeshjani** [comment]
SFSG! We might change our approach a little depending on the data.

**Comment by darshan8055** [comment]
We might change the method to asses the quality of the data.

**Comment by patelkaran002007** [comment]
Good

**Review by garima6876 — APPROVED** [review]
correct to knowledge

**Comment by ArmanShareef** [comment]
LGTM

**Pull request merged**
